<header class="page-header">
	<h1>Administration</h1>
</header>
<form method="POST">
	<div class="form-group">
		<label for="title">Title</label>
		<input name="title" type="text" autofocus class="form-control" id="title" placeholder="Title">
	</div>
	<div class="form-group">
		<label for="description">Description</label>
		<textarea name="description" class="form-control" id="description" placeholder="Description"></textarea>
	</div>
	<div class="form-group">
		<label for="priority">Priorité</label>
		<input name="priority" type="number" class="form-control" id="priority" placeholder="5" value="5" min="1" max="10">
	</div>
	<div class="form-group">
		<label for="deadline">Date Limite</label>
		<input name="deadline" type="datetime-local" class="form-control" id="deadline">
	</div>
	<button type="submit" class="btn btn-default">Submit</button>
</form>
<hr>