<!-- <h1>Administration</h1>

<h2>Créer article</h2>
<form method="POST">
	<div class="form-group">
		<label for="title">Title</label>
		<input name="title" type="text" autofocus class="form-control" id="title" placeholder="Title">
	</div>
	<div class="form-group">
		<label for="author">Author</label>
		<input name="author" type="text" class="form-control" id="author" placeholder="Author">
	</div>
	</div>
	<div class="form-group">
		<label for="content">Content</label>
		<textarea name="content" class="form-control" id="content" placeholder="Content"></textarea>
	</div>
	<div class="form-group">
  <button type="submit" class="btn btn-default">Save Draft</button>
  <button type="submit" class="btn btn-default">Preview</button>
  <button type="submit" class="btn btn-primary">Publish</button>
</div>
</form>
<hr> -->


<h1>Administration</h1>


<h2>Créer article</h2>
<form method="POST">
	<div class="form-group">
		<label for="title">Titre</label>
		<input name="title" type="title" autofocus class="form-control" id="title" placeholder="Title">
	</div>
	<div class="form-group">
		<label for="Auteur">Auteur</label>
		<input name="Auteur" type="Auteur" autofocus class="form-control" id="Auteur" placeholder="Auteur">
	</div>
	<div class="form-group">
		<label for="content">Contenu</label>
		<textarea name="content" class="form-control" id="content" placeholder="Content"></textarea>
	</div>
	<button type="submit" class="btn btn-default">Submit</button>
</form>
<hr>