<!-- single -->

<div class="container">
	<div class="row">
		<div class="col-lg-12 col-md-12">
		<div class="post-preview">
			
				<h2 class="post-title"><?=$titre?></h2>
			
			<p class="complete_article"><?=$contenu?></p>
		</div>
		</div>
	</div>
	<div class="artical-links">
			<ul>
				<li><small> </small><span><?=$date?></span></li>
				<li><a href="#"><small class="admin"> </small><span><?=$auteur?></span></a></li>
				<li><?php require('apps/actions_admin.php'); ?></li>
			</ul>
	</div>
	<h3>Commentaires</h3>
</div>