<div class="col-md-4">
	<div class="btn-group btn-group-xs">
		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			Admin <span class="caret"></span>
		</button>
		<ul class="dropdown-menu">
			<li><a href="index.php?page=admin&action=editer&id=<?=$task['id']?>"><span class="glyphicon glyphicon-pencil"></span> Editer</a></li>
			<li><a href="index.php?page=admin&action=dupliquer&id=<?=$task['id']?>"><span class="glyphicon glyphicon-copy"></span> Dupliquer</a></li>
			<li role="separator" class="divider"></li>
			<li><a href="index.php?page=admin&action=supprimer&id=<?=$task['id']?>"><span class="glyphicon glyphicon-remove"></span> Supprimer</a></li>
		</ul>
	</div>
</div>