<div class="comment-grid-top">
	<h3>Comments</h3>
	<div class="comments-top-top" id="">
		<div class="top-comment-left">
		</div>
		<div class="top-comment-right">
			<ul>
				<li><span class="left-at"><a href="#">Admin</a></span></li>
				<li><span class="right-at">June 30, 2015 at 10.30am</span></li>
				<li><a class="reply" href="#">REPLY</a></li>
			</ul>
			<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.The point of using Lorem Ipsum is that it has a more-or-less </p>
		</div>
		<div class="clearfix"> </div>
	</div>
		<div class="docs-comment-disclaimer">
		You must be logged in to post a comment.
        <a href="https://dev.mysql.com/auth/login/?dest=http%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.5%2Fen%2Fnumeric-types.html%3Facf%3D1%23add-comment" class="docs-comment-btn right">Login</a>
    	</div>
</div>
