<div class="comment-grid-top">

	<div class="comments-top-top" id="">
		<div class="top-comment-left">
		</div>
		<div class="top-comment-right">
			<ul>
				<li><span class="left-at"><?=$commentaires_auteur?></span></li>
				<li><span class="right-at"><?=$commentaires_date?></span></li>
				<?php require('apps/actions_user.php'); ?>
			</ul>
			<p><?=$commentaires_contenu?></p>
		</div>
		<div class="clearfix"> </div>
	</div>
</div>