<div class="artical-commentbox">
	<h3>Leave a comment</h3>
	<div class="table-form">
		<div class="comments-top-top" id="">
		<form>
			<input type="text" class="textbox" value="Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}">
			<textarea value="Message:" id="content-commentary" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message';}">Message</textarea>	
			<input type="submit" value="Send">
		</form>
		</div>
	</div>
</div>	