<header class="intro-header" style="background-image: url('./public/images/anes.JPG')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Les Codeurs du Dimanche</h1>
                    <hr class="small">
                    <span class="subheading">Marie, Johnny, Jonathan & Philippe</span>
                </div>
            </div>
        </div>
    </div>
</header>

<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">

        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="index.php?page=home">Home</a>
                </li>
                <li>
                    <a href="index.php?page=profile&user=<?=$_SESSION['id']?>">Profile</a>
                </li>
                <li>
                    <a href="index.php?page=admin">Admin</a>
                </li>
                <li>
                    <a href="index.php?page=logout">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
