<header class="page-header">
	<h1>Liste des tâches</h1>
	<div class="btn-group btn-group-xs">
		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			Trier par <span class="caret"></span>
		</button>
		<ul class="dropdown-menu">
			<li><a href="index.php?page=home&sort=create">Date de Création</a></li>
			<li><a href="index.php?page=home&sort=priority">Priorité</a></li>
			<li><a href="index.php?page=home&sort=deadline">Date de Réalisation</a></li>
			<li><a href="index.php?page=home&sort=author">Auteur</a></li>
		</ul>
	</div>
</header>
<div class="container">
	<div class="row">
		<?php require('apps/tasks.php'); ?>
	</div>
</div>