    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">
                    <a href="index.php?page=article&id=<?=$id?>">
                        <h2 class="post-title">
                            <?=$titre?>
                        </h2>
                        <h3 class="post-subtitle">
                            <?=$contenu?>
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="index.php?page=profile&id=<?=$id_auteur?>"><?=$auteur?></a> le <?=$date?></p>
                    <div class="btn-group btn-group-xs">
                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li><a href="index.php?page=admin&action=editer&id=<?=$id?>"><span class="glyphicon glyphicon-pencil"></span> Editer</a></li>
                                            <li role="separator" class="divider"></li>
                                            <li><a href="index.php?page=admin&action=supprimer&id=<?=$id?>"><span class="glyphicon glyphicon-remove"></span> Supprimer</a></li>
                                        </ul>
                                    </div>
                </div>
                <hr>
            </div>
        </div>
    </div>
