<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="post-preview">
                <a href="index.php?page=article&id=<?=$id?>">
                    <h2 class="post-title">
                        <?=$titre?>
                    </h2>
                    <h3 class="post-subtitle">
                        <?=$contenu?>
                    </h3>
                </a>
                <p class="post-meta">Posted by <a href="index.php?page=profile&id=<?=$id_auteur?>"><?=$auteur?></a> le <?=$date?></p>
            <?php require('apps/actions_admin.php'); ?>
            </div>
            <hr>
        </div>
    </div>
</div>
