<header class="page-header">
	<h1>Register</h1>
</header>
<form method="POST">
	<div class="form-group">
		<label for="exampleInputEmail1">Email address</label>
		<input name="email" type="email" autofocus class="form-control" id="exampleInputEmail1" placeholder="Email">
	</div>
	<div class="form-group">
		<label for="exampleInputLogin1">Login</label>
		<input name="login" type="text" autofocus class="form-control" id="exampleInputLogin1" placeholder="Login">
	</div>
	<div class="form-group">
		<label for="exampleInputPassword1">Password</label>
		<input name="password1" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
	</div>
	<div class="form-group">
		<label for="exampleInputPassword2">Retype Password</label>
		<input name="password2" type="password" class="form-control" id="exampleInputPassword2" placeholder="Retype Password">
	</div>
	<button type="submit" class="btn btn-default">Submit</button>
</form>
<hr>